Updated to support newer version of scons (#125)
* FdfToDcm does not compile on MacOS

Fixed the SConstruct so it is only built on Linux.
It uses old-style #include <backward/strstream> rather than

* Fixed scripts used to install OpenVnmrJ

Installation was generating error messages. The standard sudo is now
used. Linux obsoleted kudzu so we no longer need to deal with it.
Also copy some rpms to the dvd for installation (tcl and tk)

* build did not work with scons version 2.5.1

Current build uses scons version 2.0.1. With the newer version,
buildovj, scons gave "Found dependency cycle(s)" and "Internal
error: no cycle found" messages. The build would fail. It turned out
to be a logic error in buildMethods.py. When making symbolic links
for ".h" files, a "Depends" statement said the .h depended on the
.c file. It should be the .c depends on the .h file.
Also fixed a few warning messages and a place where data was being
written past the array limit (ipcKeyDbm.c).