build did not work with scons version 2.5.1
Current build uses scons version 2.0.1. With the newer version,
buildovj, scons gave "Found dependency cycle(s)" and "Internal
error: no cycle found" messages. The build would fail. It turned out
to be a logic error in buildMethods.py. When making symbolic links
for ".h" files, a "Depends" statement said the .h depended on the
.c file. It should be the .c depends on the .h file.
Also fixed a few warning messages and a place where data was being
written past the array limit (ipcKeyDbm.c).