Development (#134)
* ds program may show the wrong spectrum (#90)

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* allow operator names to be all-numeric strings (#93)

fix adapted from Mauro Cremonini on spinsights:
https://spinsights.chem.agilent.com/thread/3431

* Allow Cntrl-C or kill -2 to safely exit a background Vnmrbg (#95)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Server mode problem with Vnmrbg (#97)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail is their pathnames were too long (#99)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running Vnmrbg in background (#101)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running OVJ in background mode

Two macros would report errors when starting in background mode.
One error was about system not being an acquisition system.
The other error was that the file enterQ did not exist

* Fixed bug in doccplot (plot preview) that caused OpenVnmrJ to exit (#104)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running OVJ in background mode

Two macros would report errors when starting in background mode.
One error was about system not being an acquisition system.
The other error was that the file enterQ did not exist

* Bug: Plot preview could cause OpenVnmrJ to exit

If plot preview is used and another macro (from qNMR for example) calls
docpplot, magical gets into a loop and exits with a amagic: "environment nesting
is too deep" error.

* CRAFT and Bayes (#107)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running OVJ in background mode

Two macros would report errors when starting in background mode.
One error was about system not being an acquisition system.
The other error was that the file enterQ did not exist

* Bug: Plot preview could cause OpenVnmrJ to exit

If plot preview is used and another macro (from qNMR for example) calls
docpplot, magical gets into a loop and exits with a amagic: "environment nesting
is too deep" error.

* CRAFT and Bayes

Added Bayes3 programs, courtesy of Joe Ackerman and Larry Bretthorst
of Washington University. Also added sample CRAFT data from clusterlib
and fidlib.

* FdfToDcm sources (#110)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running OVJ in background mode

Two macros would report errors when starting in background mode.
One error was about system not being an acquisition system.
The other error was that the file enterQ did not exist

* Bug: Plot preview could cause OpenVnmrJ to exit

If plot preview is used and another macro (from qNMR for example) calls
docpplot, magical gets into a loop and exits with a amagic: "environment nesting
is too deep" error.

* CRAFT and Bayes

Added Bayes3 programs, courtesy of Joe Ackerman and Larry Bretthorst
of Washington University. Also added sample CRAFT data from clusterlib
and fidlib.

* Added source for FdfToDcm program

The FdfToDcm program (FDF to Dicom) is an imaging program to
generate Dicom files. See the FdfToDcm_SDD.odt file for details.
The program source is in src/dicom_fdf.

* Error plotting NOESY spectra. Issue #106 (#112)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running OVJ in background mode

Two macros would report errors when starting in background mode.
One error was about system not being an acquisition system.
The other error was that the file enterQ did not exist

* Bug: Plot preview could cause OpenVnmrJ to exit

If plot preview is used and another macro (from qNMR for example) calls
docpplot, magical gets into a loop and exits with a amagic: "environment nesting
is too deep" error.

* CRAFT and Bayes

Added Bayes3 programs, courtesy of Joe Ackerman and Larry Bretthorst
of Washington University. Also added sample CRAFT data from clusterlib
and fidlib.

* Added source for FdfToDcm program

The FdfToDcm program (FDF to Dicom) is an imaging program to
generate Dicom files. See the FdfToDcm_SDD.odt file for details.
The program source is in src/dicom_fdf.

* Fixed issue #106

There was an error printing NOESY spectra. The cause of the error
was found to be a space in a path name. This change to getpl1dinfo
fixes the specific issue but the larger problem of spaces in path
names still exists. See issue #109.

* Updated Vnmrbg (#114)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running OVJ in background mode

Two macros would report errors when starting in background mode.
One error was about system not being an acquisition system.
The other error was that the file enterQ did not exist

* Bug: Plot preview could cause OpenVnmrJ to exit

If plot preview is used and another macro (from qNMR for example) calls
docpplot, magical gets into a loop and exits with a amagic: "environment nesting
is too deep" error.

* CRAFT and Bayes

Added Bayes3 programs, courtesy of Joe Ackerman and Larry Bretthorst
of Washington University. Also added sample CRAFT data from clusterlib
and fidlib.

* Added source for FdfToDcm program

The FdfToDcm program (FDF to Dicom) is an imaging program to
generate Dicom files. See the FdfToDcm_SDD.odt file for details.
The program source is in src/dicom_fdf.

* Fixed issue #106

There was an error printing NOESY spectra. The cause of the error
was found to be a space in a path name. This change to getpl1dinfo
fixes the specific issue but the larger problem of spaces in path
names still exists. See issue #109.

* Updated Vnmrbg

Added 'rev' option to makefid to negate imaginary channel.
The makefid manual was updated.
chkname could fail if the name was longer than 255 characters.
Increased the limit to 511 characters.

* CP8 update (#116)

* ds program may show the wrong spectrum

If an arrayed data set has more than nine traces
and the  vertical scale (vs) or vertical position (vp)
is interactively updated, alternating traces will be
displayed. The integral could also be wrong.

* Allow kill -2 or Cntrl-C to safely exit a background Vnmrbg

* Vnmrbg running in server mode would exit

After receiving its first message on its server listening socket,
Vnmrbg in server mode would exit.

* Several programs would fail if file names were too long

Several programs (ddf, noise, getdatadim, ilfid) would fail
if the langth of the pathname was larger than 128 characters.
Increased length limit to 256 characters, which is what most
other programs use. Othe rsmall changes include addsub setting
ctcount=1 if it is 0.

* Error messages when running OVJ in background mode

Two macros would report errors when starting in background mode.
One error was about system not being an acquisition system.
The other error was that the file enterQ did not exist

* Bug: Plot preview could cause OpenVnmrJ to exit

If plot preview is used and another macro (from qNMR for example) calls
docpplot, magical gets into a loop and exits with a amagic: "environment nesting
is too deep" error.

* CRAFT and Bayes

Added Bayes3 programs, courtesy of Joe Ackerman and Larry Bretthorst
of Washington University. Also added sample CRAFT data from clusterlib
and fidlib.

* Added source for FdfToDcm program

The FdfToDcm program (FDF to Dicom) is an imaging program to
generate Dicom files. See the FdfToDcm_SDD.odt file for details.
The program source is in src/dicom_fdf.

* Fixed issue #106

There was an error printing NOESY spectra. The cause of the error
was found to be a space in a path name. This change to getpl1dinfo
fixes the specific issue but the larger problem of spaces in path
names still exists. See issue #109.

* Updated Vnmrbg

Added 'rev' option to makefid to negate imaginary channel.
The makefid manual was updated.
chkname could fail if the name was longer than 255 characters.
Increased the limit to 511 characters.

* Added CP8 and assorted fixes and improvements

Several new macros, bug fixes, cpmg functions for pulse
sequences (chempack.h), access to annotation tools, etc.

* Remove old versions of pi3ssbsq and pi4ssbsq macros

These are now links to pi3ssb and pi4ssb, respectively

* Added ovjUser script (#118)

This script will update the OVJ admin files in /vnmr/adm. It needs
    to be executed by the OVJ admin account (vnmr1) and takes the name
    of the user as an argument. It can be used in lieu of the admin
    interface. See comments in the script.
    Also, empty craft clusterlib and fidlib directories were missing.
    Added .keep files so git will add them.

* FdfToDcm does not compile on MacOS (#120)

Fixed the SConstruct so it is only built on Linux.
It uses old-style #include <backward/strstream> rather than

* FIxed installation scripts (#122)

* FdfToDcm does not compile on MacOS

Fixed the SConstruct so it is only built on Linux.
It uses old-style #include <backward/strstream> rather than

* Fixed scripts used to install OpenVnmrJ

Installation was generating error messages. The standard sudo is now
used. Linux obsoleted kudzu so we no longer need to deal with it.
Also copy some rpms to the dvd for installation (tcl and tk)

* Updated to support newer version of scons (#125)

* FdfToDcm does not compile on MacOS

Fixed the SConstruct so it is only built on Linux.
It uses old-style #include <backward/strstream> rather than

* Fixed scripts used to install OpenVnmrJ

Installation was generating error messages. The standard sudo is now
used. Linux obsoleted kudzu so we no longer need to deal with it.
Also copy some rpms to the dvd for installation (tcl and tk)

* build did not work with scons version 2.5.1

Current build uses scons version 2.0.1. With the newer version,
buildovj, scons gave "Found dependency cycle(s)" and "Internal
error: no cycle found" messages. The build would fail. It turned out
to be a logic error in buildMethods.py. When making symbolic links
for ".h" files, a "Depends" statement said the .h depended on the
.c file. It should be the .c depends on the .h file.
Also fixed a few warning messages and a place where data was being
written past the array limit (ipcKeyDbm.c).

* Updates based on recent SpinSights posts (#127)

* FdfToDcm does not compile on MacOS

Fixed the SConstruct so it is only built on Linux.
It uses old-style #include <backward/strstream> rather than

* Fixed scripts used to install OpenVnmrJ

Installation was generating error messages. The standard sudo is now
used. Linux obsoleted kudzu so we no longer need to deal with it.
Also copy some rpms to the dvd for installation (tcl and tk)

* build did not work with scons version 2.5.1

Current build uses scons version 2.0.1. With the newer version,
buildovj, scons gave "Found dependency cycle(s)" and "Internal
error: no cycle found" messages. The build would fail. It turned out
to be a logic error in buildMethods.py. When making symbolic links
for ".h" files, a "Depends" statement said the .h depended on the
.c file. It should be the .c depends on the .h file.
Also fixed a few warning messages and a place where data was being
written past the array limit (ipcKeyDbm.c).

* Fixed some faults discussed in SpinSights.

improved atcmd 'active' option documentation
Print Screen to a file would fail if no plotter is defined.
BioPack calibrations failed if VT unit is switched off.

* Updates from SpinSights (#132)

Added chainProshim (see manual/chainProshim)
Added menu feature to UserPrefs (see manual/UserPrefs)
Fixed svpdp to follow operator rights when making changes

* travis-ci build file (#103)

Will update according to the above comment once ovjTools are sorted out